<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Avaneesh-PC" failures="1" tests="1" name="com.bixbytes.qa.cbooster.testcases.Configure_PL_Negative_Testcases" time="41.993" errors="0" timestamp="2020-09-02T16:01:37 IST" skipped="0">
  <testcase classname="com.bixbytes.qa.cbooster.testcases.Configure_PL_Negative_Testcases" name="tc1_clickadd_withoutdata" time="41.993">
    <failure message="expected [Product type name required] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Product type name required] but found [true]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:563)
at com.bixbytes.qa.cbooster.testcases.Configure_PL_Negative_Testcases.tc1_clickadd_withoutdata(Configure_PL_Negative_Testcases.java:46)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- tc1_clickadd_withoutdata -->
  <system-out/>
</testsuite> <!-- com.bixbytes.qa.cbooster.testcases.Configure_PL_Negative_Testcases -->
